---
title: "PSY 8960 final Project"
author: "Annie Griebie"
date: "`r Sys.Date()`"
output: html_document
---
## Script Settings and Resources
```{r script_settings_and_resources, message=FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(tidyverse)
library(ggplot2)
```

## Data Import and Cleaning
```{r data_import_and_cleaning, message=FALSE}
finaldata_tbl <- readRDS("../data/finaldata_tbl.RDS")
finalskinny_tbl <- finaldata_tbl[, c("MonthlyIncome", "Attrition", "JobSatisfaction", "Department", "EducationField", "Gender", "JobRole")] %>%
  mutate(Attrition = as_factor(Attrition), Department=as_factor(Department), EducationField=as_factor(EducationField)) %>%
# renamed columns to be what I wanted to have as options within the shiny app so that it would be easier to call them and wouldn't have to rename within the app.
  rename("Turnover Status" = "Attrition") %>%
  rename("Monthly Income" = "MonthlyIncome") %>%
  rename("Education Field" = "EducationField") %>%
  rename("Job Role" = "JobRole") %>%
  rename("Job Satisfaction" = "JobSatisfaction")
```

```{r output, message=FALSE}
saveRDS(finalskinny_tbl, file="../shiny/people_dashboard/shiny_input.RDS")
```
#Include comment containing a link to app running on shinyapps.io 
An interactive web app for this data is available by [clicking this link.](insert link here)